name: 'Setup Java Environment'
description: 'Setup Java Environment'
inputs:
  java-version:
    description: 'Java Version'
    required: true
    default: '17'
  java-distribution:
    description: 'Java Distribution'
    required: true
    default: 'corretto'
runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
        cache: maven

    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
