name: Continuous Integration

on:
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: ./.github/actions/setup-java
        with:
          java-version: '17'
          java-distribution: 'corretto'

      - name: Unit Test
        run: mvn clean test
        working-directory: ./sample-api

  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: ./.github/actions/setup-java
        with:
          java-version: '17'
          java-distribution: 'corretto'

      - name: Check
        run: date

      - name: Build
        run: mvn clean install -Dmaven.test.skip=true
        working-directory: ./sample-api

      - name: Integration Test
        run: mvn -P integration-test clean verify
        working-directory: ./integration-test

      - name: Clean up Docker images
        if: always()
        run: docker-compose down --rmi all --volumes
        continue-on-error: true
